### ISSUE TITLE
can;t find words.pkl

### ISSUE THREAD

**Issue by kevtheprogrammer** [AkankshaJagdish/medchatbot#1]
FileNotFoundError: [Errno 2] No such file or directory: 'words.pkl'

**Comment by AkankshaJagdish** [comment]
Did you run the training?

You must run train_chatbot.py located [here](https://github.com/AkankshaJagdish/medchatbot/blob/main/training_chatbot/train_chatbot.py), and then transfer the files created: words.pkl, etc to the backend folder.

**Comment by AkankshaJagdish** [comment]
As it seems your problem has been solved, I'm closing this issue.
