### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by Keethukumar** [AkankshaJagdish/medchatbot#2]
words.pkl, classes.pkl, chatbot5

**Comment by AkankshaJagdish** [comment]
Those files will be generated when you run train_chatbot.py in training_chatbot folder. 

You must then copy and paste them into prediction.

**Comment by AkankshaJagdish** [comment]
chatbotmodel.h5 can be generated after running chat.py, or main.py.

**Comment by AkankshaJagdish** [comment]
Closing issue as there do not seem to be any more doubts.
